// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rguvsjpqvswmpsngrxmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndXZzanBxdnN3bXBzbmdyeG1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMTI0MjIsImV4cCI6MjA1MTg4ODQyMn0.pCFG0o-hKPc6Hqbr_Iqt1GFXZD9FoslCcXN4YJSAu2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);